# Copyright (c) 2025 VoidCanary-Lab
# SPDX-License-Identifier: GPL-3.0-or-later

---
- name: Configure Gateway
  hosts: gateway
  become: yes
  tasks:
    - name: Install Cloudflared
      apt:
        name: cloudflared
        state: present

- name: Configure Vault
  hosts: vault
  become: yes
  tasks:
    - name: Install Wazuh Agent
      apt:
        name: wazuh-agent
        state: present