# Copyright (c) 2025 VoidCanary-Lab
# SPDX-License-Identifier: GPL-3.0-or-later

name: Gateware Verification

on: [push, pull_request]

jobs:
  formal-proof:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Install Python Deps
        run: pip install amaranth[builtin-yosys]==0.4 amaranth-yosys==0.35.0.0.post81

      - name: Run Formal Verification (BMC)
        run: |
          cd gateware/verify
          python3 proof.py

  simulation-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install amaranth[builtin-yosys]==0.4 amaranth-yosys==0.35.0.0.post81
      - name: Run Unit Tests
        run: python3 -m unittest discover gateware/tests
