# Copyright (c) 2025 VoidCanary-Lab
# SPDX-License-Identifier: GPL-3.0-or-later

name: Infrastructure Lint

on: [push, pull_request]

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform fmt -check -recursive infrastructure/terraform

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ansible
        run: pip install ansible
      - name: Install Ansible collections
        run: ansible-galaxy collection install -r infrastructure/ansible/requirements.yml
      - name: Run Ansible Lint
        uses: ansible/ansible-lint@v6
        with:
          args: "infrastructure/ansible/"